apiVersion: v1
kind: Template
labels:
  app.kubernetes.io/part-of: fom
  template: fom-object-storage-secret
metadata:
  name: fom-object-storage-secret
parameters:
  # Mandatory parameters
  - name: BUCKET
    required: true
  - name: ACCESS_ID
    required: true
  - name: SECRET
    required: true
  - name: ENV
    required: true
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      # No suffix as it is the same settings for all FOM instances for a given environment.
      name: fom-object-storage-${ENV}
    stringData:
      # The unqualified hostname is the name of the db service. Easier to look up in fom-api-deploy than recreate.
      bucket: ${BUCKET}
      access_id: ${ACCESS_ID}
      secret: ${SECRET}
