version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.local
    restart: always
    working_dir: /usr/src/app
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
      - DB_NAME=fom
      - DB_TYPE=postgres
      - DB_HOST=localhost
      - DB_SSL=false
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - '8081:3333'
    tty: true
    command: 'npm run start:api'
    depends_on:
      - db
    networks:
      - backend
    links:
      - 'db:database'
  db:
    container_name: fom-db
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile.local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fom
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=5342
    volumes:
      - ms-postgres-data:/var/lib/postgres/data
    ports:
      - '5432:5432'
      - '443:443'
      - '80:80'
    networks:
      - backend
networks:
  backend:
volumes:
  ms-postgres-data:

