/**
 * FOM API
 * API for FOM backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProjectPlanCodeFilterEnum = 'FSP' | 'WOODLOT' | 'ALL';

export const ProjectPlanCodeFilterEnum = {
    Fsp: 'FSP' as ProjectPlanCodeFilterEnum,
    Woodlot: 'WOODLOT' as ProjectPlanCodeFilterEnum,
    All: 'ALL' as ProjectPlanCodeFilterEnum
};

