# Based on https://github.com/BCDevOps/platform-services/blob/master/apps/pgsql/patroni/openshift/deployment.yaml
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |-
      Patroni Postgresql database cluster, with persistent storage.
    iconClass: icon-postgresql
    openshift.io/display-name: Patroni Postgresql (Persistent)
    openshift.io/long-description: This template deploys a patroni postgresql HA
      cluster with persistent storage.
    tags: postgresql
  name: patroni-pgsql-persistent
labels:
  app: ${NAME}${SUFFIX}
  phase: deploy
  app.kubernetes.io/instance: ${NAME}${SUFFIX}
  app.kubernetes.io/component: database
  app.kubernetes.io/name: patroni  
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/part-of: fom
  template: fom-ha-db-deploy

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      # Set to true to allow local image name resolution, without having to specify the internal OpenShift image registry and port.
      local: true

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      cluster-name: ${NAME}${SUFFIX}
    name: ${NAME}-master${SUFFIX}
  spec:
    ports:
    - port: 5432
#      name: 'postgresql'
      protocol: TCP
      targetPort: 5432
    selector:
      cluster-name: ${NAME}${SUFFIX}
      role: master
      app.kubernetes.io/name: patroni
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: null
    generation: 3
    labels:
      cluster-name: ${NAME}${SUFFIX}
    name: ${NAME}${SUFFIX}
  spec:
    triggers: 
#      - type: ImageChange
#        imageChangeParams:
#          automatic: true
#          containerNames:
#            - postgresql
#          from:
#            kind: ImageStreamTag
#            name: ${NAME}:${IMAGE_STREAM_VERSION}
      - type: ConfigChange
    podManagementPolicy: OrderedReady
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        statefulset: ${NAME}${SUFFIX}
    serviceName: ${NAME}${SUFFIX}
    template:
      metadata:
        creationTimestamp: null
        labels:
          statefulset: ${NAME}${SUFFIX}
          cluster-name: ${NAME}${SUFFIX}
          app.kubernetes.io/name: patroni
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: statefulset
                  operator: In
                  values: 
                  - ${NAME}${SUFFIX}
              topologyKey: "kubernetes.io/hostname"
        containers:
        - env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: PATRONI_KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: PATRONI_KUBERNETES_LABELS
            value: '{"cluster-name": "${NAME}${SUFFIX}", "app.kubernetes.io/name": "patroni"}'
          - name: PATRONI_SUPERUSER_USERNAME
            valueFrom:
              secretKeyRef:
                key: superuser-username
                name: ${NAME}${SUFFIX}
          - name: PATRONI_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: superuser-password
                name: ${NAME}${SUFFIX}
          - name: PATRONI_REPLICATION_USERNAME
            valueFrom:
              secretKeyRef:
                key: replication-username
                name: ${NAME}${SUFFIX}
          - name: PATRONI_REPLICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                key: replication-password
                name: ${NAME}${SUFFIX}
          - name: APP_USER
            valueFrom:
              secretKeyRef:
                key: app-db-username
                name: ${NAME}${SUFFIX}
          - name: APP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: app-db-password
                name: ${NAME}${SUFFIX}
          - name: APP_DATABASE
            valueFrom:
              secretKeyRef:
                key: app-db-name
                name: ${NAME}${SUFFIX}
          - name: PATRONI_SCOPE
            value: ${NAME}${SUFFIX}
          - name: PATRONI_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: PATRONI_LOG_LEVEL
            value: WARNING
          - name: PATRONI_POSTGRESQL_DATA_DIR
            value: /home/postgres/pgdata/pgroot/data
          - name: PATRONI_POSTGRESQL_PGPASS
            value: /tmp/pgpass
          - name: PATRONI_POSTGRESQL_LISTEN
            value: 0.0.0.0:5432
          - name: PATRONI_RESTAPI_LISTEN
            value: 0.0.0.0:8008
          image: ${NAME}:${IMAGE_STREAM_TAG}
          imagePullPolicy: Always
          name: postgresql
          ports:
          - containerPort: 8008
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            failureThreshold: 4
            exec:
              command:
                - /usr/share/scripts/patroni/health_check.sh
          volumeMounts:
          - mountPath: /home/postgres/pgdata
            name: postgresql
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccountName: ${NAME}${SUFFIX}
        terminationGracePeriodSeconds: 0
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS}
        labels:
          app: ${NAME}${SUFFIX}
        name: postgresql
      spec:
        storageClassName: ${STORAGE_CLASS}
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${PVC_SIZE}

parameters:
- description: The name of the application for labelling all artifacts.
  displayName: Application Name
  name: NAME
  value: patroni
- name: SUFFIX
  description: A suffix appended to all artifact's name (NAME)
- name: REPLICAS
  displayName: REPLICAS
  description: The number of statefulSet replicas to use.
  value: '3'
- description: Starting amount of CPU the container can use.
  displayName: CPU REQUEST
  name: CPU_REQUEST
  value: '250m'
- description: Maximum amount of CPU the container can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  value: '1'
- description: Starting amount of memory the container can use.
  displayName: Memory Request
  name: MEMORY_REQUEST
  value: 512Mi
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 512Mi
- name: IMAGE_STREAM_TAG
  description: Patroni ImageTag
  value: patroni:v11-stable
- description: The size of the persistent volume to create.
  displayName: Persistent Volume Size
  name: PVC_SIZE
  # 3+ years production-like volume of projects (without comments, interactions) in test environment is ~170 MiB so default 1 Gi should be sufficient for at least 1+ years.
  value: 1Gi
- name: STORAGE_CLASS
  value: netapp-block-standard
