apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Forest Operations Map"
    tags: "fom"
    iconClass: icon-js
labels:
  app: ${NAME}-${ZONE}
  app.kubernetes.io/part-of: ${NAME}-${ZONE}
parameters:
  - name: NAME
    description: Product name
    value: fom
  - name: COMPONENT
    description: Component name
    value: db
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: POSTGRES_DB
    description: Postgres database name
    value: fom
  - name: POSTGRES_PASSWORD
    description: Password for the PostgreSQL connection user.
    from: "[a-zA-Z0-9]{16}"
    generate: expression
  - name: POSTGRES_USER
    description: Postgres user
    value: postgres
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}-${COMPONENT}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-db: ${POSTGRES_DB}
      database-password: ${POSTGRES_PASSWORD}
      database-user: ${POSTGRES_USER}
