apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}-batch
  annotations:
    description: "Forest Operations Map"
    tags: "fom"
    iconClass: icon-js
labels:
  app: ${NAME}-${ZONE}
  app.kubernetes.io/part-of: ${NAME}-${ZONE}
parameters:
  - name: NAME
    description: Product name
    value: fom
  - name: COMPONENT
    description: Component name
    value: api
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - description: Environment corresponding to namespace (dev/test/prod)
    displayName: Environment
    name: ENV
    value: dev
  - description: URL of Object Storage Service.
    displayName: Object Storage URL
    name: OBJECT_STORAGE_URL
    value: "nrs.objectstore.gov.bc.ca"
  - name: CPU_REQUEST
    value: 50m
  - name: MEMORY_REQUEST
    value: 50Mi
  - name: CRON_MINUTES
    description: Random number, 0-60, for scheduling cronjobs
    from: "[0-5]{1}[0-9]{1}"
    generate: expression
objects:
  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata:
      name: ${NAME}-${ZONE}
    spec:
      concurrencyPolicy: Replace
      schedule: "${CRON_MINUTES} 9 * * * " # Run daily at 9:xx AM UTC
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                cronjob: ${NAME}-${ZONE}
            spec:
              restartPolicy: OnFailure
              containers:
                - name: batch
                  image: ${NAME}-${ZONE}-${COMPONENT}:${ZONE}-api
                  imagePullPolicy: Always
                  args: ["-batch"]
                  env:
                    - name: DB_HOST
                      value: ${NAME}-${ZONE}-db
                    - name: DB_NAME
                      valueFrom:
                        secretKeyRef:
                          key: database-db
                          name: ${NAME}-${ZONE}-db
                    - name: DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: database-password
                          name: ${NAME}-${ZONE}-db
                    - name: DB_USERNAME
                      valueFrom:
                        secretKeyRef:
                          key: database-user
                          name: ${NAME}-${ZONE}-db
                    - name: OBJECT_STORAGE_ACCESS_ID
                      valueFrom:
                        secretKeyRef:
                          key: access_id
                          name: fom-object-storage-${ENV}
                    - name: OBJECT_STORAGE_BUCKET
                      valueFrom:
                        secretKeyRef:
                          key: bucket
                          name: fom-object-storage-${ENV}
                    - name: OBJECT_STORAGE_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: secret
                          name: fom-object-storage-${ENV}
                    - name: OBJECT_STORAGE_URL
                      value: ${OBJECT_STORAGE_URL}
                  resources:
                    requests:
                      cpu: ${CPU_REQUEST}
                      memory: ${MEMORY_REQUEST}
