apiVersion: apps/v1
kind: Deployment
metadata:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: fom-819
    app.kubernetes.io/part-of: fom-819
  name: fom-819-db-prev
  namespace: a4b31c-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: fom-819-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fom-819
        deployment: fom-819-db
      name: fom-819-db-prev
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: database-db
              name: fom-819-db-prev
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: fom-819-db-prev
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: fom-819-db-prev
        - name: RANDOM_EXPRESSION
          value: lSavApQ5NVX6INVcxC7f0skE5HByWGuB
        image: ghcr.io/bcgov/nr-fom/db:819
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: fom
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 30m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: fom-819-db-prev
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fom-819-db-prev
        persistentVolumeClaim:
          claimName: fom-819-db
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-26T19:24:20Z"
    lastUpdateTime: "2025-06-26T19:24:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    type: Available
  - lastTransitionTime: "2025-06-26T19:22:50Z"
    lastUpdateTime: "2025-06-26T19:24:20Z"
    message: ReplicaSet "fom-819-db-79cd78984" has successfully progressed.
    reason: NewReplicaSetAvailable
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
