apiVersion: v1
kind: Template
labels:
  template: fom-api-deploy
  app: fom
  app-component: ${NAME}
  tag: ${TAG}
  app.kubernetes.io/part-of: fom
metadata:
  name: fom-api-deploy
parameters:
  - description: Environment corresponding to namespace (dev/test/prod).
    displayName: Environment
    name: ENV
    value: dev
  - description: OpenShift Project (namespace prefix).
    displayName: Project
    name: PROJECT
    value: a4b31c
  - description: Name of the application component being deployed.
    displayName: Name
    name: NAME
    value: fom-api
  - description: Tag (e.g. release/build) being deployed. Changing tag not tested, might break.
    displayName: Tag
    name: TAG
    value: main
  - description: Port number
    displayName: Port number
    name: PORT
    value: '3333'
  - description: Service port name (referenced by route).
    displayName: Service port name
    name: SERVICE_PORT_NAME
    value: http
  - description: Request for CPU resources measured in cpu units, e.g. 200m
    displayName: CPU resource request
    name: REQUEST_CPU
    required: false
    value: 50m
  - description: Request for memory resources measured in bytes, e.g. 512Mi, 1Gi.
    displayName: Memory resource request
    name: REQUEST_MEMORY
    required: false
    value: 50Mi
  - description: Limit for CPU resources measured in cpu units, e.g. 200m
    displayName: CPU resource limit
    name: LIMIT_CPU
    required: false
    value: 200m
  - description: Limit for memory resources measured in bytes, e.g. 512Mi, 1Gi.
    displayName: Memory resource limit
    name: LIMIT_MEMORY
    required: false
    value: 1Gi
  - description: Number of replicas
    displayName: Replica Count
    name: REPLICA_COUNT
    required: false
    value: '2'
  - description: DNS Hostname for the public route. For dev should default to nr-fom-${NAME}-${TAG}-${ENV}. (But can't use other parameters in default value.)
    displayName: DNS Hostname
    name: HOSTNAME
    required: true
  - description: API Image Version to use
    displayName: API Image Version
    name: IMAGE_STREAM_VERSION
    required: true
    value: main
  - description: Specify 'true' to populate test data (run test migrations) at startup.
    displayName: Database Test Data
    name: DB_TESTDATA
    value: 'false'
  
objects:
    # ConfigMap - Hostname - for lookup by Admin/Public
  - kind: ConfigMap
    apiVersion: v1
    data: 
      hostname: ${HOSTNAME}.apps.silver.devops.gov.bc.ca
    metadata:
      name: ${NAME}-${TAG}-${ENV}

  ### DeploymentConfig
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: ${NAME}-${TAG}-${ENV}
    spec:
      replicas: ${{REPLICA_COUNT}}
      revisionHistoryLimit: 10
      test: false
      strategy:
        type: Rolling
        rollingParams:
          # Delay pod updates to account for time to run migrations
          updatePeriodSeconds: 10
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
      selector:
        deploymentconfig: ${NAME}-${TAG}-${ENV}
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - app
            from:
              kind: ImageStreamTag
              namespace: ${PROJECT}-tools
              name: ${NAME}:${IMAGE_STREAM_VERSION}
        - type: ConfigChange
      template:
        metadata:
          creationTimestamp: null
          labels:
            deploymentconfig: ${NAME}-${TAG}-${ENV}
        spec:
          containers:
            - name: app
              # Supply a space to image:, will use settings in ImageChange trigger.
              image:  
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: fom-db-${TAG}-${ENV}
                - name: DB_USERNAME 
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: fom-db-${TAG}-${ENV}
                - name: DB_NAME
                  valueFrom:
                      secretKeyRef:
                        key: database-name
                        name: fom-db-${TAG}-${ENV}
                - name: DB_HOST
                  valueFrom:
                      secretKeyRef:
                        key: database-host
                        name: fom-db-${TAG}-${ENV}
                - name: DB_TESTDATA
                  value: ${DB_TESTDATA}
                # This is the application port
                - name: PORT
                  value: '${PORT}'
              resources:
                requests:
                  cpu: ${REQUEST_CPU}
                  memory: ${REQUEST_MEMORY}
                limits:
                  cpu: ${LIMIT_CPU}
                  memory: ${LIMIT_MEMORY}
              # Have longer delay at startup to allow for database migrations to take place.
              startupProbe:
                httpGet:
                  path: /api
                  port: ${{PORT}}
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 10
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /api
                  port: ${{PORT}}
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /api
                  port: ${{PORT}}
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
  ### Service
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG}
    spec:
      ports:
        - name: ${SERVICE_PORT_NAME}
          protocol: TCP
          port: ${{PORT}}
          targetPort: ${{PORT}}
      selector:
        deploymentconfig: ${NAME}-${TAG}-${ENV}
      type: ClusterIP
      sessionAffinity: None
  ### Route
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG}
      annotations: 
        haproxy.router.openshift.io/rate-limit-connections: "true"
        # Number of HTTP requests that a client IP can make in a 3-second period
        haproxy.router.openshift.io/rate-limit-connections.rate-http: "5"
    spec:
      host: ${HOSTNAME}.apps.silver.devops.gov.bc.ca
      to:
        kind: Service
        name: ${NAME}-${TAG}
        weight: 100
      port:
        targetPort: ${SERVICE_PORT_NAME}
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  ### Network Policy - External Web Traffic
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: web-allow-external-${NAME}-${TAG}
    spec:
      podSelector:
        matchLabels:
          deploymentconfig: ${NAME}-${TAG}-${ENV}
      ingress:
        - {}
  ### Network Policy - App to DB Traffic
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: app-to-db-allow-${NAME}-${TAG}
    spec:
      podSelector:
        matchLabels:
          deploymentconfig: fom-db-${TAG}-${ENV}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  deploymentconfig: ${NAME}-${TAG}-${ENV}
          ports:
            - protocol: TCP
              port: 5432
