apiVersion: v1
kind: Template
labels:
  template: fom-batch-deploy
  app: fom
  app-component: ${NAME}
  # Need prefix for suffix in case it starts with a dash or is empty. Label values aren't allowed to start with a dash.
  suffix: fom${SUFFIX}
  app.kubernetes.io/part-of: fom
metadata:
  name: fom-batch-deploy
parameters:
  - description: Environment corresponding to namespace (dev/test/prod).
    displayName: Environment
    name: ENV
    value: dev
  - description: OpenShift Project (namespace prefix).
    displayName: Project
    name: PROJECT
    value: a4b31c
  - description: Name of the application component being deployed.
    displayName: Name
    name: NAME
    value: fom-batch
  - description: Name of the database component used by the batch.
    displayName: Database Name
    name: DB_NAME
    value: fom-db
  - description: Suffix specifying the release/build/environment. Can be blank. Example '-working-dev'
    displayName: Suffix
    name: SUFFIX
    value: -main-dev
  - description: Request for CPU resources measured in cpu units, e.g. 200m
    displayName: CPU resource request
    name: REQUEST_CPU
    required: false
    value: 50m
  - description: Request for memory resources measured in bytes, e.g. 512Mi, 1Gi.
    displayName: Memory resource request
    name: REQUEST_MEMORY
    required: false
    value: 50Mi
  - description: Limit for CPU resources measured in cpu units, e.g. 200m
    displayName: CPU resource limit
    name: LIMIT_CPU
    required: false
    value: 200m
  - description: Limit for memory resources measured in bytes, e.g. 512Mi, 1Gi.
    displayName: Memory resource limit
    name: LIMIT_MEMORY
    required: false
    value: 1Gi
  - description: API Image Version to use
    displayName: API Image Version
    name: IMAGE_STREAM_VERSION
    required: true
    value: main
objects:
  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata: 
      name: ${NAME}${SUFFIX}
    spec:
      concurrencyPolicy: Replace
      # Timezone used for Cron schedule appears to be UTC. We want this process to run early morning BC time, which is -7 UTC ignoring daylights savings. So 9am UTC should be good enough.
      schedule: '0 9 * * * ' # Run at 9:00am UTC each day. 
      #schedule: '*/1 * * * * ' # Run every minute for testing.
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                cronjob: ${NAME}${SUFFIX}
            spec:
              restartPolicy: OnFailure
              containers:
                - name: batch
                  # Cron Jobs don't support ImageChangeTriggers, so we explicitly specify the image, with a policy of pull always so it should always use the 
                  # most up-to-date image.
                  image: "image-registry.openshift-image-registry.svc:5000/${PROJECT}-tools/fom-api:${IMAGE_STREAM_VERSION}"  
                  imagePullPolicy: Always
                  args: ["-batch"] 
                  env:
                    - name: DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: database-password
                          name: ${DB_NAME}${SUFFIX}
                    - name: DB_USERNAME 
                      valueFrom:
                        secretKeyRef:
                          key: database-user
                          name: ${DB_NAME}${SUFFIX}
                    - name: DB_NAME
                      valueFrom:
                          secretKeyRef:
                            key: database-name
                            name: ${DB_NAME}${SUFFIX}
                    - name: DB_HOST
                      valueFrom:
                          secretKeyRef:
                            key: database-host
                            name: ${DB_NAME}${SUFFIX}
                    # We don't supply the data encryption key because the batch process doesn't need to interact with encrypted data.
                    # We don't supply keycloak configuration because the batch process doesn't need to interact with Keycloak.
                  resources:
                    requests:
                      cpu: ${REQUEST_CPU}
                      memory: ${REQUEST_MEMORY}
                    limits:
                      cpu: ${LIMIT_CPU}
                      memory: ${LIMIT_MEMORY}
  ### Network Policy - App to DB Traffic
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: app-to-db-allow-${NAME}${SUFFIX}
    spec:
      podSelector:
        matchLabels:
          deploymentconfig: ${DB_NAME}${SUFFIX}
      ingress:
        - from:
           - podSelector:
               matchLabels:
                 cronjob: ${NAME}${SUFFIX}
          ports:
            - protocol: TCP
              port: 5432
