name: .Deploys

on:
  workflow_call:
    inputs:
      ### Required
      target:
        description: Target for deploy; usually PR number, test or prod
        required: true
        type: string

      ### Typical / recommended
      # autoscaling:
      #   description: Autoscaling enabled or not for the deployments
      #   required: false
      #   type: string
      #   default: true
      # environment:
      #   description: Environment name; omit for PRs
      #   required: false
      #   type: string
      # tag:
      #   description: Container tag; usually PR number
      #   required: false
      #   type: string
      #   default: ${{ github.event.number }}
      triggers:
        description: Paths to trigger a deploy; omit=always; e.g. ('backend/' 'frontend/')
        required: false
        type: string

      # ### Usually a bad idea / not recommended
      # directory:
      #   description: 'Chart directory'
      #   default: 'charts/${{ github.event.repository.name }}'
      #   required: false
      #   type: string
      # timeout-minutes:
      #   description: 'Timeout minutes'
      #   default: 10
      #   required: false
      #   type: number
      # values:
      #   description: 'Values file'
      #   default: 'values.yaml'
      #   required: false
      #   type: string
      # params:
      #   description: 'Extra parameters to pass to helm upgrade'
      #   default: ''
      #   required: false
      #   type: string

# env:
#   repo_release: ${{ github.event.repository.name }}-${{ inputs.release }}
#   package_tag: ${{ inputs.tag }}

jobs:
  deploys:
    name: Deploys
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      matrix:
        name: [api, admin, db, libs, public]
        include:
          - name: api
            parameters:
              -p OC_NAMESPACE=${{ vars.OC_NAMESPACE }}
              -p CERTBOT=false -p REPLICA_COUNT=1
              -p FOM_EMAIL_NOTIFY=SIBIFSAF@victoria1.gov.bc.ca
              -p DB_TESTDATA=true
              -p AWS_USER_POOLS_WEB_CLIENT_ID="7hpo4qa7j0hs0rkfl2pm0sto5k"
              -p LOGOUT_CHAIN_URL="https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri="
          - name: admin
            parameters: -p CERTBOT=false -p REPLICA_COUNT=1
          - name: db
            overwrite: false
          - name: libs
            overwrite: false
          - name: public
            parameters: -p CERTBOT=false -p REPLICA_COUNT=1
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v2.0.0
        with:
          file: ${{ matrix.name }}/openshift.deploy.yml
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          penetration_test: false
          parameters:
            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:${{ inputs.target }}
            -p URL=fom-${{ inputs.target }}.apps.silver.devops.gov.bc.ca
            -p ZONE=${{ inputs.target }} ${{ matrix.parameters }}
          triggers: ${{ inputs.triggers }}
