name: Demo

on:
  push:
    branches: [demo]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  builds:
    name: DEMO Builds
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [admin, api, db, public]
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.0.1
        with:
          package: ${{ matrix.package }}
          build_context: ./
          build_file: ${{ matrix.package }}/Dockerfile
          tag: demo
          token: ${{ secrets.GITHUB_TOKEN }}

  deploys:
    name: DEMO Deploys
    needs: [builds]
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml
    with:
      aws_id: "k3b9ip1vf85o4tkqvu5g4adgj"
      batch_secret: "fom-demo-client-app-api"
      environment: test
      fom_email: "FLNR.AdminServicesCariboo@gov.bc.ca"
      logout_url: "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri="
      replicas: 3
      tag: demo
      target: demo
      testdata: true
      url: fom-demo.apps.silver.devops.gov.bc.ca
