name: DEMO (merge)

on:
  push:
    branches: demo

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [admin, api, db, public]
        include:
          - package: admin
            build_context: ./
            build_file: admin/Dockerfile
          - package: api
            build_context: ./
            build_file: api/Dockerfile
          - package: db
          - package: public
            build_context: ./
            build_file: public/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - uses: bcgov-nr/action-builder-ghcr@v2.3.0
        with:
          package: ${{ matrix.package }}
          build_context: ${{ matrix.build_context }}
          build_file: ${{ matrix.build_file }}
          keep_versions: 100
          tag: demo
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy (DEMO)
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml
    with:
      aws_user_pools_web_client_id: k3b9ip1vf85o4tkqvu5g4adgj
      batch_client_rfsh_api_tkn_op_secret_name: fom-demo-client-app-api
      db_testdata: true
      environment: demo
      email_notify: FLNR.AdminServicesCariboo@gov.bc.ca
      logout_chain_url: https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri=
      tag: demo
      target: demo
      url: fom-demo.apps.silver.devops.gov.bc.ca
