name: Merge to Demo

on:
  pull_request:
  # push:
  #   branches: [demo]

env:
  ZONE: demo

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [admin, api, db, public]
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.0.1
        with:
          package: ${{ matrix.package }}
          build_context: ./
          build_file: ${{ matrix.package }}/Dockerfile
          tag: ${{ env.ZONE }}
          token: ${{ secrets.GITHUB_TOKEN }}

  deploys:
    name: DEMO Deploys
    needs: [builds]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      aws_user_pools_web_client_id: "k3b9ip1vf85o4tkqvu5g4adgj"
      batch_secret: "fom-demo-client-app-api"
      db_testdata: true
      fom_email: "FLNR.AdminServicesCariboo@gov.bc.ca"
      logout_url: "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri="
      target: ${{ github.event.number }}
      url: fom-demo.apps.silver.devops.gov.bc.ca
