name: TEST (merge)

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/*"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  deploy:
    name: Deploy (TEST)
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml
    with:
      aws_user_pools_web_client_id: k3b9ip1vf85o4tkqvu5g4adgj
      batch_client_rfsh_api_tkn_op_secret_name: fom-demo-client-app-api
      db_testdata: true
      environment: test
      email_notify: FLNR.AdminServicesCariboo@gov.bc.ca
      logout_chain_url: https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri=
      target: test
      url: fom-test.nrs.gov.bc.ca

  images-promote:
    name: Promote images (TEST)
    continue-on-error: true # If no prod tags
    needs: [deploy]
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        component: [api, admin, db, public]
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.component }}
          target: ${{ needs.deploy.outputs.tag }}
          tags: test
