name: PR Closed

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  cleanup:
    name: Cleanup and Images
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-close.yml@v0.9.0
    secrets:
      oc_namespace: ${{ vars.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      cleanup: label
      packages: api public admin db
      cleanup_name: fom
