name: Cleanup

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  NAME: fom
  REPONAME: greenfield-template

jobs:
  cleanup-openshift:
    name: Cleanup OpenShift
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Remove OpenShift artifacts
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}

          # Remove old build runs, build pods and deployment pods
          oc delete all,pvc,secret -l app=${{ env.NAME }}-${{ github.event.number }}
