name: Pull Request Closed

on:
  pull_request:
    types:
      - closed
    paths-ignore:
      - ".github/graphics/**"
      - ".github/ISSUE_TEMPLATE/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Tag images for promotion on GitHub Container Registry (ghcr.io)
  image-promotions:
    name: Tag images
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        component: [api, admin, db, public]
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          target: ${{ github.event.number }}-${{ matrix.component }}
          tags: test-${{ matrix.component }}

  merge-notification:
    name: Merge Notification
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Pre-merge update
        uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allow-repeats: false
          message: |
            Your Pull Request code is being promoted!  Please follow the link below.
            [Merge to Main Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)

  cleanup-openshift:
    name: Cleanup OpenShift
    runs-on: ubuntu-22.04
    env:
      NAME: fom
    steps:
      - uses: actions/checkout@v3
      - name: Remove OpenShift artifacts
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.OC_NAMESPACE }}

          # Remove old build runs, build pods and deployment pods
          oc delete all,pvc,secret,cm -l app=${{ env.NAME }}-${{ github.event.number }}

      - name: Remove KeyCroak Redirect URL for Admin
        uses: bcgov/nr-keycloak-redirect@main
        id: del-keycroak
        with:
          add_delete: "del"
          redirect: https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/*
          secret: ${{ secrets.KC_SECRET }}
          clientid: ${{ secrets.KC_CLIENTID }}
          clientid_2: "fom"
          realm: ${{ secrets.KC_REALM }}
          host: ${{ secrets.KC_HOST }}
