name: PR Close

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  cleanup:
    name: Cleanup and Images
    uses: bcgov/actions-openshift/.github/workflows/.pr-close.yml@75454b2b33edf37135f6f167775c77a3414207f6 # v0.3.0
    secrets:
      oc_namespace: ${{ vars.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      cleanup: label
      packages: api public admin db
      cleanup_name: fom-${{ github.event.number }}
