name: PR Close

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  cleanup:
    name: Cleanup and Images
    uses: bcgov/actions-openshift/.github/workflows/.pr-close.yml@50414269295ed040baf0d05cb4c7f4d76c7bcd8c # v0.2.0
    secrets:
      oc_namespace: ${{ vars.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      cleanup: label
      packages: api public admin db
      cleanup_name: fom-${{ github.event.number }}
