name: PR

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    uses: ./.github/workflows/.build.yml
    with:
      tag: ${{ github.event.number }}
      tag_fallback: test

  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      tag: ${{ github.event.number }}
      target: ${{ github.event.number }}
      triggers: ('db/' 'libs/' 'api/' 'admin/' 'public/')
      url: "fom-$(( ${{ github.event.number }} % 50 )).apps.silver.devops.gov.bc.ca"
