name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  NAME: fom

jobs:
  build-db:
    name: Build-DB
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: db/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.number }}-db
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-api:
    name: Build-API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.number }}-api
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-public:
    name: Build-Public
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Public Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: public/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.number }}-public
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-admin:
    name: Build-Admin
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Admin Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: admin/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.number }}-admin
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-dev:
    name: Deploy-Dev
    needs:
      - build-db
      - build-api
      - build-admin
      - build-public
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set -eux

          # Login to OpenShift and select project
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}

          # Init (db secret), only if necessary
          oc process -f .github/openshift/init.database.yml -p ZONE=${{ github.event.number }} \
            | oc create -f - || \
            echo "Already initialized"

          # Process and apply deployment templates
          oc process -f .github/openshift/deploy.database.yml -p ZONE=${{ github.event.number }} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-db | oc apply -f -
          oc process -f .github/openshift/deploy.api.yml -p ZONE=${{ github.event.number }} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-api -p DB_TESTDATA=true \
            | oc apply -f -
          oc process -f .github/openshift/deploy.admin.yml -p ZONE=${{ github.event.number }} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-admin \
            | oc apply -f -
          oc process -f .github/openshift/deploy.public.yml -p ZONE=${{ github.event.number }} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-public \
            | oc apply -f -

          # Follow any active rollouts (see deploymentconfigs)
          oc rollout status dc/${{ env.NAME }}-${{ github.event.number }}-db -w
          oc rollout status dc/${{ env.NAME }}-${{ github.event.number }}-api -w
          oc rollout status dc/${{ env.NAME }}-${{ github.event.number }}-admin -w
          oc rollout status dc/${{ env.NAME }}-${{ github.event.number }}-public -w

      - name: Deployment update
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            [Dev - api](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/api) available
            [Dev - admin](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/admin) available
            [Dev - public](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/public) available

          allow-repeats: false

  deploy-test:
    name: Deploy-Test
    needs:
      - deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      ZONE: test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set -eux
          # Login to OpenShift and select project
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}
          # Init (db secret), only if necessary
          oc process -f .github/openshift/init.database.yml -p ZONE=${ZONE} \
            | oc create -f - || \
            echo "Already initialized"
          # Process and apply deployment templates
          oc process -f .github/openshift/deploy.database.yml -p ZONE=${ZONE} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-db | oc apply -f -
          oc process -f .github/openshift/deploy.api.yml -p ZONE=${ZONE} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-api -p DB_TESTDATA=true \
            | oc apply -f -
          oc process -f .github/openshift/deploy.admin.yml -p ZONE=${ZONE} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-admin \
            | oc apply -f -
          oc process -f .github/openshift/deploy.public.yml -p ZONE=${ZONE} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-public \
            | oc apply -f -
          # Follow any active rollouts (see deploymentconfigs)
          oc rollout status dc/${{ env.NAME }}-${ZONE}-db -w
          oc rollout status dc/${{ env.NAME }}-${ZONE}-api -w
          oc rollout status dc/${{ env.NAME }}-${ZONE}-admin -w
          oc rollout status dc/${{ env.NAME }}-${ZONE}-public -w

      - name: Deployment update
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            [test - api](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/api) available
            [test - admin](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/admin) available
            [test - public](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/public) available

          allow-repeats: false

  deploy-prod:
    name: Deploy-Prod
    needs:
      - deploy-test
    runs-on: ubuntu-latest
    environment:
      name: prod
    env:
      ZONE: prod
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set -eux
          # Login to OpenShift and select project
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}
          # Init (db secret), only if necessary
          oc process -f .github/openshift/init.database.yml -p ZONE=${ZONE} \
            | oc create -f - || \
            echo "Already initialized"
          # Process and apply deployment templates
          oc process -f .github/openshift/deploy.database.yml -p ZONE=${ZONE} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-db | oc apply -f -
          oc process -f .github/openshift/deploy.api.yml -p ZONE=${ZONE} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-api -p DB_TESTDATA=true \
            | oc apply -f -
          oc process -f .github/openshift/deploy.admin.yml -p ZONE=${ZONE} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-admin \
            | oc apply -f -
          oc process -f .github/openshift/deploy.public.yml -p ZONE=${ZONE} \
            -p PROMOTE=${{ github.repository }}:${{ github.event.number }}-public \
            | oc apply -f -
          # Follow any active rollouts (see deploymentconfigs)
          oc rollout status dc/${{ env.NAME }}-${ZONE}-db -w
          oc rollout status dc/${{ env.NAME }}-${ZONE}-api -w
          oc rollout status dc/${{ env.NAME }}-${ZONE}-admin -w
          oc rollout status dc/${{ env.NAME }}-${ZONE}-public -w

      - name: Deployment update
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            [prod - api](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/api) available
            [prod - admin](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/admin) available
            [prod - public](https://${{ env.NAME }}-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/public) available

          allow-repeats: false
