name: Pull Request Open

on:
  pull_request:

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  init:
    name: Init
    permissions:
      pull-requests: write
    runs-on: ubuntu-24.04
    outputs:
      route_number: ${{ steps.calculate.outputs.route_number }}
    steps:
      - name: Calculate the deployment number
        id: calculate
        run: |
          echo "route_number=$((${{ github.event.number }} % 50))" >> $GITHUB_OUTPUT

      - name: OpenShift Init
        uses: bcgov-nr/action-deployer-openshift@v3.0.1
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: libs/openshift.init.yml
          overwrite: false
          parameters: -p ZONE=${{ github.event.number }}
          triggers: ('db/' 'libs/' 'api/' 'admin/' 'public/')  

  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [admin, api, db, public]
        include:
          - package: admin
            build_context: ./
            build_file: admin/Dockerfile
            triggers: ('admin/' 'libs/')
          - package: api
            build_context: ./
            build_file: api/Dockerfile
            triggers: ('api/' 'libs/')
          - package: db
            triggers: ('db')
          - package: public
            build_context: ./
            build_file: public/Dockerfile
            triggers: ('public/' 'libs/')
    steps:
      - uses: actions/checkout@v4
      - uses: bcgov-nr/action-builder-ghcr@v2.3.0
        with:
          package: ${{ matrix.package }}
          build_context: ${{ matrix.build_context }}
          build_file: ${{ matrix.build_file }}
          keep_versions: 100
          tag: ${{ github.event.number }}
          tag_fallback: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ${{ matrix.triggers }}

  deploy:
    name: Deploy (${{ github.event.number }})
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/.deploy.yml

  results:
    name: PR Results
    needs: [build, deploy]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
