name: PR

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

env:
  FOM_ROUTE: $(( ${{ github.event.number }} % 50 ))

jobs:
  init:
    name: Initialize
    outputs:
      route: ${{ github.event.number }}
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Get FAM Route
        id: route
        run: |
          echo "route=$(( ${{ github.event.number }} % 50 ))" >> $GITHUB_OUTPUT

  # builds:
  #   name: Builds
  #   runs-on: ubuntu-22.04
  #   permissions:
  #     packages: write
  #   strategy:
  #     matrix:
  #       package: [admin, api, db, public]
  #       include:
  #         - package: admin
  #           triggers: ('admin/' 'libs/')
  #         - package: api
  #           triggers: ('api/' 'libs/')
  #         - package: db
  #           triggers: ('db')
  #         - package: public
  #           triggers: ('public/' 'libs/')
  #   steps:
  #     - uses: bcgov-nr/action-builder-ghcr@v2.0.1
  #       with:
  #         package: ${{ matrix.package }}
  #         build_context: ./
  #         build_file: ${{ matrix.package }}/Dockerfile
  #         keep_versions: 100
  #         tag: ${{ github.event.number }}
  #         tag_fallback: test
  #         triggers: ${{ matrix.triggers }}

  # https://github.com/bcgov-nr/action-deployer-openshift
  deploys:
    name: Deploys
    # needs: [builds]
    needs: [init]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      target: ${{ github.event.number }}
      triggers: ('db/' 'libs/' 'api/' 'admin/' 'public/')
      url: fom-${{ needs.init.outputs.route }}.apps.silver.devops.gov.bc.ca
      test: "$(( ${{ github.event.number }} % 50 ))"
