name: PR Validate

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr-description-add:
    name: PR Description Add
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    timeout-minutes: 1
    steps:
      - name: Get FAM Route
        id: fam
        run: echo "route=$(( ${{ github.event.number }} % 50 ))" >> $GITHUB_OUTPUT

      - uses: bcgov-nr/action-pr-description-add@v1.1.2
        env:
          DOMAIN: apps.silver.devops.gov.bc.ca
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---
            Thanks for the PR!

            Any successful deployments (not always required) will be available below.
             - [api](https://fom-${{ steps.fam.outputs.route }}.${{ env.DOMAIN }}/api)
             - [admin](https://fom-${{ steps.fam.outputs.route }}.${{ env.DOMAIN }}/admin)
             - [public](https://fom-${{ steps.fam.outputs.route }}.${{ env.DOMAIN }}/public)

            Once merged, code will be promoted and handed off to following workflow run.
             - [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)
